### ISSUE TITLE
Update Token脚本一直Error: Process completed with exit code 1

### ISSUE THREAD

**Issue by wang4632** [wangziyingwen/AutoApi#22]
报错显示：
Run python UpdateToken.py
Traceback (most recent call last):
<<<<<<<<<<<<<<<配置信息更新中>>>>>>>>>>>>>>>
  File "UpdateToken.py", line 140, in <module>
增加账号中
    account['ms_token'][a]=getmstoken(a)
更新邮箱
  File "UpdateToken.py", line 82, in getmstoken
<<<<<<<<<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>>>>>>
    refresh_token = jsontxt['refresh_token']
公钥获取成功
KeyError: 'refresh_token'
账号/应用 1 的微软密钥获取失败
请检查secret里 account_ID , account_SECRET , MS_TOKEN 格式与内容是否正确，然后重新设置
Error: Process completed with exit code 1.

按照教程提示：这里应该填写 应用id,应用密码,微软密钥(refresh_token)

反复检查了，发现填写的格式应没问题（用半角逗号隔开）。
然后应用id,应用密码没错（从注册的应用那里复制下来，并且可以使用在线版工具获取refresh_token）
然后，这里微软密钥(refresh_token)就是用在线工具提取出来的。

所以不知道什么问题，请指教？

**Comment by wang4632** [comment]
已解决，用了自定义REDIRECT_URL，但是忘了设置secret
